version: '3'

services:
  web:
    build: .
    command: python backend/server.py
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
  rasa:
    image: rasa/rasa:2.8.1-full
    ports:
      - "5005:5005"
    volumes:
      - ./rasa:/app
    command:
      - rasa
      - run
      - --enable-api
      - --cors
      - "*"
      - --debug
  action_server:
    image: rasa/rasa-sdk:2.8.1
    volumes:
      - ./rasa/actions:/app/actions
    ports:
      - "5055:5055"
    command:
      - rasa
      - run
